// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyInventory.Data;

#nullable disable

namespace PharmacyInventory.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    partial class PharmacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PharmacyInventory.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PasswordHash = "ig0za9XUfGfivqDJZVwMNw==.uQFoojQzPCOSISW3e1fHJXTyNGqnv9u6mPd3/lvE4f4=",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PasswordHash = "SOKIlfjxDfqkENFT+Xu1tQ==.x/P2E9uTI+l04R9RioWn3SCwcSmLg4csIgSzTmiS3Mw=",
                            Role = 2,
                            Username = "cashier"
                        });
                });

            modelBuilder.Entity("PharmacyInventory.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("PharmacyInventory.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BuyingPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Distributor")
                        .HasColumnType("TEXT");

                    b.Property<string>("DosageForm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExdDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenericName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroceryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .HasColumnType("TEXT");

                    b.Property<string>("MfdDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoOfPacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoOfUnits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutColour")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PackPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("Packing")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricePerQuantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("Speciality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Strength")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitsPerPack")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("BrandName");

                    b.HasIndex("Category");

                    b.HasIndex("GenericName");

                    b.HasIndex("ItemType");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PharmacyInventory.Models.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CashierUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SoldAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CashierUserId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("PharmacyInventory.Models.SaleItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("PharmacyInventory.Models.Sale", b =>
                {
                    b.HasOne("PharmacyInventory.Models.AppUser", "CashierUser")
                        .WithMany("Sales")
                        .HasForeignKey("CashierUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashierUser");
                });

            modelBuilder.Entity("PharmacyInventory.Models.SaleItem", b =>
                {
                    b.HasOne("PharmacyInventory.Models.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyInventory.Models.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PharmacyInventory.Models.AppUser", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PharmacyInventory.Models.Product", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("PharmacyInventory.Models.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
